-- MySQL Script generated by MySQL Workbench
-- 02/26/15 02:05:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema conforg_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema conforg_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conforg_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `conforg_db` ;

-- -----------------------------------------------------
-- Table `conforg_db`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`company` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`company` (
  `Company_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Company_name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Company_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`users` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `lastname` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `email_temp` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `password_temp` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `code` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `active` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`company_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`company_user` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`company_user` (
  `company_user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_id` INT(11) NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`company_user_id`),
  INDEX `company_user_id_foreign_idx` (`user_id` ASC),
  INDEX `company_company_id_foreign_idx` (`company_id` ASC),
  CONSTRAINT `company_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `conforg_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `company_company_id_foreign`
    FOREIGN KEY (`company_id`)
    REFERENCES `conforg_db`.`company` (`Company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`conference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`conference` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`conference` (
  `conf_id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `begin_date` DATE NOT NULL,
  `begin_time` DATETIME NOT NULL,
  `end_date` DATE NOT NULL,
  `end_time` DATETIME NOT NULL,
  `is_free` BIT(1) NOT NULL DEFAULT b'0',
  `cutoff_time` DATETIME NULL DEFAULT NULL,
  `min_score` DOUBLE NULL DEFAULT NULL,
  `ticket_price` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`conf_id`),
  UNIQUE INDEX `Title` (`title` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`interest_field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`interest_field` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`interest_field` (
  `interestfield_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `remarks` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`interestfield_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`conference_field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`conference_field` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`conference_field` (
  `conferencefield_id` INT(11) NOT NULL AUTO_INCREMENT,
  `conf_id` INT(11) NOT NULL,
  `interestfield_id` INT(11) NOT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`conferencefield_id`),
  INDEX `conference_field_conf_id_foreign_idx` (`conf_id` ASC),
  INDEX `conference_field_interestfield_id_foreign_idx` (`interestfield_id` ASC),
  CONSTRAINT `conference_field_conf_id_foreign`
    FOREIGN KEY (`conf_id`)
    REFERENCES `conforg_db`.`conference` (`conf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `conference_field_interestfield_id_foreign`
    FOREIGN KEY (`interestfield_id`)
    REFERENCES `conforg_db`.`interest_field` (`interestfield_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`venue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`venue` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`venue` (
  `venue_id` INT(11) NOT NULL AUTO_INCREMENT,
  `venue_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `venue_address` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `latitude` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `longitude` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `company_id` INT(11) NULL DEFAULT NULL,
  `available` VARCHAR(45) NOT NULL DEFAULT 'yes',
  PRIMARY KEY (`venue_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`room` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`room` (
  `room_id` INT(11) NOT NULL AUTO_INCREMENT,
  `venue_id` INT(11) NOT NULL,
  `room_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `capacity` INT(45) NULL DEFAULT NULL,
  `rental_cost` DECIMAL(12,2) NULL DEFAULT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`room_id`, `venue_id`),
  INDEX `room_venue_id_foreign_idx` (`venue_id` ASC),
  CONSTRAINT `room_venue_id_foreign`
    FOREIGN KEY (`venue_id`)
    REFERENCES `conforg_db`.`venue` (`venue_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`conference_room_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`conference_room_schedule` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`conference_room_schedule` (
  `confroomschedule_id` INT(11) NOT NULL AUTO_INCREMENT,
  `conf_id` INT(11) NULL DEFAULT NULL,
  `room_id` INT(11) NULL DEFAULT NULL,
  `description` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `date_start` DATE NULL DEFAULT NULL,
  `date_end` DATE NULL DEFAULT NULL,
  `begin_time` DATETIME NULL DEFAULT NULL,
  `end_time` DATETIME NULL DEFAULT NULL,
  `remarks` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`confroomschedule_id`),
  INDEX `conference_room_schedule_conf_id_foreign_idx` (`conf_id` ASC),
  INDEX `conference_room_schedule_room_id_foreign_idx` (`room_id` ASC),
  CONSTRAINT `conference_room_schedule_conf_id_foreign`
    FOREIGN KEY (`conf_id`)
    REFERENCES `conforg_db`.`conference` (`conf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `conference_room_schedule_room_id_foreign`
    FOREIGN KEY (`room_id`)
    REFERENCES `conforg_db`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`conference_topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`conference_topic` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`conference_topic` (
  `topic_id` INT(11) NOT NULL AUTO_INCREMENT,
  `conf_id` INT(11) NOT NULL,
  `topic_name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`topic_id`),
  INDEX `conference_topic_conf_id_foreign_idx` (`conf_id` ASC),
  CONSTRAINT `conference_topic_conf_id_foreign`
    FOREIGN KEY (`conf_id`)
    REFERENCES `conforg_db`.`conference` (`conf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`roles` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`roles` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rolename` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `remarks` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `roles_rolename_unique` (`rolename` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`confuserrole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`confuserrole` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`confuserrole` (
  `confuserrole_id` INT(10) NOT NULL AUTO_INCREMENT,
  `role_id` INT(10) NOT NULL,
  `user_id` INT(10) NOT NULL,
  `conf_id` INT(11) NOT NULL,
  PRIMARY KEY (`confuserrole_id`),
  INDEX `confuserrole_role_id_index_01` (`role_id` ASC),
  INDEX `confuserrole_user_id_index_02` (`user_id` ASC),
  INDEX `confuserrole_conf_id_foreign` (`conf_id` ASC),
  CONSTRAINT `confuserrole_conf_id_foreign`
    FOREIGN KEY (`conf_id`)
    REFERENCES `conforg_db`.`conference` (`conf_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `confuserrole_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `conforg_db`.`roles` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `confuserrole_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `conforg_db`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `conforg_db`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`countries` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`countries` (
  `country_id` INT(5) NOT NULL AUTO_INCREMENT,
  `short_name` VARCHAR(80) NOT NULL DEFAULT '',
  `long_name` VARCHAR(80) NOT NULL DEFAULT '',
  `calling_code` VARCHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `conforg_db`.`equipment_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`equipment_category` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`equipment_category` (
  `equipmentcategory_id` INT(11) NOT NULL AUTO_INCREMENT,
  `equipmentcategory_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `equipmentcategory_remark` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`equipmentcategory_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`equipment` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`equipment` (
  `equipment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `equipmentcategory_id` INT(11) NOT NULL DEFAULT '0',
  `equipment_name` VARCHAR(45) NULL DEFAULT NULL,
  `equipment_remark` VARCHAR(45) NULL DEFAULT NULL,
  `rental_cost` VARCHAR(45) NULL DEFAULT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`equipment_id`, `equipmentcategory_id`),
  INDEX `equipment_equipmentcategory_id_foreign_idx` (`equipmentcategory_id` ASC),
  CONSTRAINT `equipment_equipmentcategory_id_foreign`
    FOREIGN KEY (`equipmentcategory_id`)
    REFERENCES `conforg_db`.`equipment_category` (`equipmentcategory_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `conforg_db`.`invitation` 0 remove user_id`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`invitation` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`invitation` (
  `invite_id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `company` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`invite_id`),
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`invoice` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`invoice` (
  `invoice_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `conf_id` INT(11) NOT NULL,
  `quantity` INT(3) NOT NULL,
  `price` FLOAT NOT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `total` FLOAT NULL DEFAULT NULL,
  `status` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT 'unpaid',
  PRIMARY KEY (`invoice_id`),
  INDEX `invoice_conf_id_foreign_idx` (`conf_id` ASC),
  INDEX `invoice_user_id_foreign_idx` (`user_id` ASC),
  CONSTRAINT `invoice_conf_id_foreign`
    FOREIGN KEY (`conf_id`)
    REFERENCES `conforg_db`.`conference` (`conf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `invoice_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `conforg_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`submissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`submissions` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`submissions` (
  `sub_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `conf_id` INT(11) NOT NULL,
  `sub_type` INT(11) NOT NULL,
  `sub_title` VARCHAR(220) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `sub_abstract` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `attachment_path` VARCHAR(220) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `sub_remarks` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `status` TINYINT(1) NOT NULL COMMENT '1 = accepted, 9 = rejected, 0 = on review',
  `overall_score` INT(11) NOT NULL DEFAULT '0',
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`sub_id`),
  UNIQUE INDEX `submissions_subtitle_unique` (`sub_title` ASC),
  CONSTRAINT `submission_conf_id_foreign`
    FOREIGN KEY ()
    REFERENCES `conforg_db`.`conference` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `submission_user_id_foreign`
    FOREIGN KEY ()
    REFERENCES `conforg_db`.`users` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`keywords` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`keywords` (
  `keyword_id` INT(11) NOT NULL AUTO_INCREMENT,
  `keyword_name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `sub_id` INT(11) NOT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`keyword_id`, `sub_id`),
  INDEX `keywords_sub_id_foreign_idx` (`sub_id` ASC),
  CONSTRAINT `keywords_sub_id_foreign`
    FOREIGN KEY (`sub_id`)
    REFERENCES `conforg_db`.`submissions` (`sub_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`payment` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`payment` (
  `payment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `invoice_id` INT(11) NOT NULL,
  `amount` FLOAT NOT NULL,
  `payment_type` INT(11) NOT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `payment_invoice_id_foreign_idx` (`invoice_id` ASC),
  CONSTRAINT `payment_invoice_id_foreign`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `conforg_db`.`invoice` (`invoice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`pending`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`pending` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`pending` (
  `pending_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `equipment_id` INT(11) NULL DEFAULT NULL,
  `equipmentcategory_id` INT(11) NULL DEFAULT NULL,
  `room_id` INT(11) NULL DEFAULT NULL,
  `venue_id` INT(11) NULL DEFAULT NULL,
  `status` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `avaliable` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`pending_id`),
  INDEX `pending_user_id_foreign_idx` (`user_id` ASC),
  INDEX `pending_equipment_id_foreign_idx` (`equipment_id` ASC),
  INDEX `pending_equipmentcategory_id_foreign_idx` (`equipmentcategory_id` ASC),
  INDEX `pending_room_id_foreign_idx` (`room_id` ASC),
  INDEX `pending_venue_id_foreign_idx` (`venue_id` ASC),
  CONSTRAINT `pending_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `conforg_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pending_equipment_id_foreign`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `conforg_db`.`equipment` (`equipment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pending_equipmentcategory_id_foreign`
    FOREIGN KEY (`equipmentcategory_id`)
    REFERENCES `conforg_db`.`equipment_category` (`equipmentcategory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pending_room_id_foreign`
    FOREIGN KEY (`room_id`)
    REFERENCES `conforg_db`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pending_venue_id_foreign`
    FOREIGN KEY (`venue_id`)
    REFERENCES `conforg_db`.`venue` (`venue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`permissions` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`permissions` (
  `permission_Id` INT(11) NOT NULL,
  `permission_name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `permission_remarks` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`permission_Id`),
  UNIQUE INDEX `permission_name_UNIQUE` (`permission_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`profiles` -removed the country_id` 
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`profiles` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`profiles` (
  `profile_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fb_email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `user_id` INT(11) NOT NULL,
  `uid` BIGINT(20) UNSIGNED NOT NULL,
  `access_token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `bio` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `location` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `photo` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL, 
  PRIMARY KEY (`profile_id`),
  INDEX `profiles_user_id_foreign_idx` (`user_id` ASC),
  INDEX `profiles_country_id_foreign_idx` (`country_id` ASC),
  CONSTRAINT `profiles_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `conforg_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`reviews` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`reviews` (
  `review_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sub_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `internal_comment` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `comment` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `quality_score` INT(11) NOT NULL,
  `relevance_score` INT(11) NOT NULL,
  `originality_score` INT(11) NOT NULL,
  `significance_score` INT(11) NOT NULL,
  `presentation_score` INT(11) NOT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `reviews_sub_id_foreign_idx` (`sub_id` ASC),
  INDEX `reviews_user_id_foreign_idx` (`user_id` ASC),
  CONSTRAINT `reviews_sub_id_foreign`
    FOREIGN KEY (`sub_id`)
    REFERENCES `conforg_db`.`submissions` (`sub_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reviews_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `conforg_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`role_permission` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`role_permission` (
  `rolepermission_id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_id` INT(11) NULL DEFAULT NULL,
  `permission_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`rolepermission_id`),
  INDEX `role_permission_role_id_foreign_idx` (`role_id` ASC),
  INDEX `role_permission_permission_id_foreign_idx` (`permission_id` ASC),
  CONSTRAINT `role_permission_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `conforg_db`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_permission_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `conforg_db`.`permissions` (`permission_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`room_equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`room_equipment` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`room_equipment` (
  `roomequipment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `room_id` INT(11) NULL DEFAULT NULL,
  `equipment_id` INT(11) NULL DEFAULT NULL,
  `quantity` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `remarks` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`roomequipment_id`),
  INDEX `room_equipment_equipment_id_foreign_idx` (`equipment_id` ASC),
  INDEX `room_equipment_roomt_id_foreign_idx` (`room_id` ASC),
  CONSTRAINT `room_equipment_equipment_id_foreign`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `conforg_db`.`equipment` (`equipment_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `room_equipment_room_id_foreign`
    FOREIGN KEY (`room_id`)
    REFERENCES `conforg_db`.`room` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`submission_authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`submission_authors` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`submission_authors` (
  `sub_id` INT(11) NOT NULL,
  `email` VARCHAR(220) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `first_name` VARCHAR(220) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `last_name` VARCHAR(220) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `organization` VARCHAR(220) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `is_presenting` TINYINT(1) NOT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`sub_id`, `email`),
  UNIQUE INDEX `submission_author_email_unique` (`email` ASC),
  CONSTRAINT `submission_authors_sub_id_foreign`
    FOREIGN KEY (`sub_id`)
    REFERENCES `conforg_db`.`submissions` (`sub_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`submission_topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`submission_topic` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`submission_topic` (
  `topic_id` INT(11) NOT NULL,
  `sub_id` INT(11) NOT NULL,
  `created_by` INT(11) NOT NULL,
  `modified_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`topic_id`, `sub_id`),
  INDEX `submission_topic_sub_id_foreign_idx` (`sub_id` ASC),
  CONSTRAINT `submission_topic_topic_id_foreign`
    FOREIGN KEY (`topic_id`)
    REFERENCES `conforg_db`.`conference_topic` (`topic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `submission_topic_sub_id_foreign`
    FOREIGN KEY (`sub_id`)
    REFERENCES `conforg_db`.`submissions` (`sub_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`sysrole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`sysrole` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`sysrole` (
  `sysrole_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `role_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`sysrole_id`),
  INDEX `sysrole_user_id_foreign_idx` (`user_id` ASC),
  INDEX `sysrole_role_id_foreign_idx` (`role_id` ASC),
  CONSTRAINT `sysrole_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `conforg_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sysrole_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `conforg_db`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `conforg_db`.`conference_schedule_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`conference_schedule_event` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`conference_schedule_event` (
  `conference_schedule_event_id` INT(11) NOT NULL AUTO_INCREMENT,
  `conference_room_schedule_id` INT(11) NOT NULL,
  `submission_id` INT(11) NOT NULL,
  `title` VARCHAR(1000) NOT NULL,
  `day` DATE NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `className` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`conference_schedule_event_id`),
  INDEX `conference_schedule_event_submission_id_foreign_idx` (`submission_id` ASC),
  INDEX `conference_schedule_event_conference_room_schedule_id_forei_idx` (`conference_room_schedule_id` ASC),
  CONSTRAINT `conference_schedule_event_submission_id_foreign`
    FOREIGN KEY (`submission_id`)
    REFERENCES `conforg_db`.`submissions` (`sub_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `conference_schedule_event_conference_room_schedule_id_foreign`
    FOREIGN KEY (`conference_room_schedule_id`)
    REFERENCES `conforg_db`.`conference_room_schedule` (`confroomschedule_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `conforg_db`.`invitation_to_conference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conforg_db`.`invitation_to_conference` ;

CREATE TABLE IF NOT EXISTS `conforg_db`.`invitation_to_conference` (
  `invitation_to_conference_id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `role_id` INT(11) NULL DEFAULT NULL,
  `conf_id` INT(11) NULL DEFAULT NULL,
  `is_used` BIT(1) NOT NULL DEFAULT b'0',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`invitation_to_conference_id`),
  INDEX `invitation_to_conference_conf_id_foreign_idx` (`conf_id` ASC),
  INDEX `invitation_to_conference_role_id_foreign_idx` (`role_id` ASC),
  CONSTRAINT `invitation_to_conference_conf_id_foreign`
    FOREIGN KEY (`conf_id`)
    REFERENCES `conforg_db`.`conference` (`conf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `invitation_to_conference_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `conforg_db`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

USE `conforg_db`;

DELIMITER $$

USE `conforg_db`$$
DROP TRIGGER IF EXISTS `conforg_db`.`conference_BEFORE_INSERT` $$
USE `conforg_db`$$
CREATE TRIGGER `conference_BEFORE_INSERT` BEFORE INSERT ON `conference`
 FOR EACH ROW IF(NEW.cutoff_time IS NULL) THEN
BEGIN
SET NEW.cutoff_time = DATE_SUB(DATE_ADD(DATE_ADD(NEW.begin_date, INTERVAL 1 MONTH), INTERVAL 1 DAY), INTERVAL 1 second) ;
END;
END if$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
